config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get '/created_today' => 'welcome#created_today'

  resources :subjects, except: :new do
    resources :areas, except: :index
  end

  resources :scientists do
    resources :quotes
  end
  resources :quotes
  get '/jolly' => 'welcome#jolly', :as => :jolly

  resources :scientists do
    resources :theorems
  end

  resources :theorems do
    resources :corollaries
  end

  post '/corollaries/:id/unsave_corollary' => 'corollaries#unsave_corollary', :as => :unsave_corollary
  post '/corollaries/:id/save_corollary' => 'corollaries#save_corollary', :as => :save_corollary
  get '/scientists/:id/unsave_scientist' => 'scientists#unsave_scientist', :as => :unsave_scientist
  get '/scientists/:id/save_scientist' => 'scientists#save_scientist', :as => :save_scientist
  get '/top_3' => 'welcome#top_3', :as => :top_3
  get '/theorems/:id/unsave_theorem' => 'theorems#unsave_theorem', :as => :unsave_theorem
  get '/theorems/:id/save_theorem' => 'theorems#save_theorem', :as => :save_theorem

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :destroy]
  get '/users/:id/make_admin' => 'users#make_admin'
  get '/users/:id/areas_created' => 'users#areas_created'
  get '/users/:id/subjects_created' => 'users#subjects_created'
  get '/users/:id/theorems_created' => 'users#theorems_created'
  get '/users/:id/scientists_created' => 'users#scientists_created'
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :scientist
  validates_presence_of :text
  validates_uniqueness_of :text
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :save_quote, :unsave_quote]
  before_action :set_scientist, only: [:new, :create, :edit, :destroy]
  before_action :check_admin, only: [:edit, :destroy]

  def index
    if set_scientist
      @quotes = @scientist.quotes.order(scientist_id: :desc)
      render :template => "quotes/_quotes_display", layout: false
    else
      @quotes = Quote.all.order(scientist_id: :desc)
    end
  end

  def show
  end

  def new
    @quote = @scientist.quotes.build
    render :layout => false
  end

  def create
    @quote = @scientist.quotes.build(quote_params)
    if @quote.save
      respond_to do |format|
        format.js   {render :layout => false}
        format.html {redirect_to @quote, notice: 'Quote was successfully created.'}
      end
    else
      respond_to do |format|
        format.html { render 'new', notice: @quote.errors.full_messages.first }
        format.js   { render json: @quote.errors}
      end
    end
  end

  def edit
    respond_to do |format|
      format.html { redirect_to edit_quote_path(@quote) }
      format.js   { render :layout => false }
    end
  end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to @quote, notice: 'Quote was successfully updated!' }
        format.js { render layout: false }
      end
    else
      respond_to do |format|
        format.html { render 'edit'}
        format.js {}
      end
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to @scientist, notice: 'Quote was successfully deleted!' }
      format.js   { render :layout => false }
    end
  end

  def save_quote
    if current_user.add_to_fav(@quote)
      redirect_to @quote, notice: "Quote successfully added to Favorites"
    end
  end

  def unsave_quote
    if current_user.remove_from_fav(@quote)
      redirect_to @quote, notice: "Quote successfully removed from Favorites"
    end
  end

  private

  def set_scientist
    @scientist = Scientist.find_by(id: params[:id]) || @scientist = Scientist.find_by(id: params[:scientist_id])
  end

  def set_quote
    @quote = Quote.find_by(id: params[:id])
  end

  def quote_params
    params.require(:quote).permit(:text, :scientist_id, :created_by)
  end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<% if @quote.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@quote.errors.count, "error") %>
      prohibited this Quote from being saved:
    </h2>
    <ul>
    <% @quote.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>

<%= form_for [@scientist, @quote], :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <h4><%= f.label :text, "Quote:", class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :text, :required => true, class: "form-control" %>
    </div>
  </div>

  <%= f.hidden_field :created_by, :value => current_user.email %>

  <%= f.submit "Submit", class: "btn btn-default btn-primary", id: "submit-button" %>
<% end %>

app/views/quotes/_quote_display.html.erb
  <h3 id="quoteText"><%= @quote.text %></h3>
  <strong>By: <h4 id="quoteScientist"><%= link_to @quote.scientist.full_name, @quote.scientist %></h4></strong>
  <% if current_user.admin? %>
    <strong>Created By: </strong><h4 id="createdBy"><%= link_to @quote.created_by, user_by_email(@quote.created_by) %></h4>
  <% end %>

app/views/quotes/_quote_summary.html.erb
<div class="quote" id="quote-<%= q.id%>">
  <h4 style="text-align: center;"><%= link_to (truncate q.text), scientist_quote_path(q.scientist, q) %></h4>
  <div style="text-align: center;"><strong>By: <%= link_to q.scientist.full_name, q.scientist %></strong></div>
  <div class="admin-info" style="text-align: center;">
    <% if current_user.admin? %>
      <strong><p>Created by: <%= link_to q.created_by, user_by_email(q.created_by) %></p></strong>
      <div id="edit-<%= q.id%>" style="display: inline;"><strong><%= link_to "Edit", edit_scientist_quote_path(q.scientist, q), class: "btn btn-primary btn-xs", id: "edit-button" %></strong></div>
      <div id="delete-<%= q.id%>" style="display: inline;"><strong><%= button_to "Destroy", [q.scientist, q], class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"} %></strong></div>
      <div id="edit-quote-<%= q.id%>-div"></div>
    <% end %>
  </div>
  <div id="line" style="margin-right:auto; margin-left:auto;"></div>
</div>

app/views/quotes/_quotes_display.html.erb
<div class="frame">
  <div class="all-quotes">
    <% if !@quotes.empty? %>
      <ul>
        <% @quotes.each do |q| %>
          <%= render partial: 'quotes/quote_summary', locals: {q: q} %>
        <% end %>
      </ul>
    <% else %>
      <h3 id="empty">Currently there are no quotes to show</h3>
    <% end %>
  </div>
</div>

app/views/quotes/create.js.erb
var html = "<%= j render 'quotes/quote_summary', q: @quote %>"
if (document.getElementById("empty")) {
  $('h3#empty').replaceWith(html)
  $('#form_for_quote').hide();
} else {
  $("div.all-quotes ul").append(html)
  $('#form_for_quote').hide();
}

app/views/quotes/destroy.js.erb
$('div#quote-<%=@quote.id %>').remove();

app/views/quotes/edit.html.erb
<h1>Edit Quote:</h1>

<br><br><br><br><br><br><br>

<div class="frame">
  <div class="new-quote-form">
    <%= render partial: 'form', locals: { scientist: @scientist, quote: @quote} %>
  </div>
</div>

app/views/quotes/edit.js.erb
$('body').off('click');
if( $("#edit-quote-<%= @quote.id%>-div").children().length == 0 ) {
  $("#edit-quote-<%= @quote.id%>-div").html("<%= j render 'quotes/form', quote: @quote %>");
} else {
  $("#edit-quote-<%= @quote.id%>-div").toggle();
}

app/views/quotes/index.html.erb
<h1>Quotes</h1>

<br><br><br><br><br><br><br>

<%= render partial: 'quotes_display', locals: {quotes: @quotes} %>

app/views/quotes/jolly.html.erb
<h1>Quote</h1>

<br><br><br><br>

<div class="frame">
  <div id="jolly_quote_div">
    <h4>Are you ready for it?</h4>
  </div>
</div>

<br>

<div id="back-button">
  <%= link_to 'Jolly button', jolly_path, id: "jolly-button", class: "btn btn-primary" %>
</div>

app/views/quotes/jolly.js.erb
$("#jolly_quote_div").html("<%= j render 'quotes/quote_display', quote: @quote %>")

app/views/quotes/new.html.erb
<div class="frame">
  <div class="new-quote-form">
    <%= render partial: 'form', locals: { scientist: @scientist, quote: @quote} %>
  </div>
</div>

app/views/quotes/show.html.erb
<h1>Quote</h1>

<br><br><br><br><br>

<div class="frame">
  <div class="show-quote">
    <%= render partial: 'quote_display', locals: {quote: @quote} %>
  </div>
</div>

app/views/quotes/update.js.erb
$("#quote-<%= @quote.id%>").html("<%= j render 'quotes/quote_summary', q: @quote %>");
$("#edit-quote-<%= @quote.id%>-div").hide();