config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get '/created_today' => 'welcome#created_today'

  resources :subjects, except: :new do
    resources :areas, except: :index
  end

  resources :scientists do
    resources :quotes
  end
  resources :quotes
  get '/jolly' => 'welcome#jolly', :as => :jolly

  resources :scientists do
    resources :theorems
  end

  resources :theorems do
    resources :corollaries
  end

  post '/corollaries/:id/unsave_corollary' => 'corollaries#unsave_corollary', :as => :unsave_corollary
  post '/corollaries/:id/save_corollary' => 'corollaries#save_corollary', :as => :save_corollary
  get '/scientists/:id/unsave_scientist' => 'scientists#unsave_scientist', :as => :unsave_scientist
  get '/scientists/:id/save_scientist' => 'scientists#save_scientist', :as => :save_scientist
  get '/top_3' => 'welcome#top_3', :as => :top_3
  get '/theorems/:id/unsave_theorem' => 'theorems#unsave_theorem', :as => :unsave_theorem
  get '/theorems/:id/save_theorem' => 'theorems#save_theorem', :as => :save_theorem

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :destroy]
  get '/users/:id/make_admin' => 'users#make_admin'
  get '/users/:id/areas_created' => 'users#areas_created'
  get '/users/:id/subjects_created' => 'users#subjects_created'
  get '/users/:id/theorems_created' => 'users#theorems_created'
  get '/users/:id/scientists_created' => 'users#scientists_created'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery except: :jolly

  def home
    redirect_to current_user if user_signed_in?
  end

  def jolly
    @quote = Quote.all.sample
    respond_to do |format|
      format.js {render '/quotes/jolly.js'}
      format.html {render '/quotes/jolly'}
    end
  end

  def created_today
    @theorems = Theorem.created_today
    @scientists = Scientist.created_today
    render '/welcome/todays'
  end

  def top_3
    @scientists_array = Scientist.top_3_scientists
    @theorems_array = Theorem.top_3_theorems
    render '/scientists/top_3'
  end
end

app/views/welcome/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="https://upload.wikimedia.org/wikipedia/commons/e/e7/Georg_Cantor2.jpg" alt="Cantor">
      <div class="carousel-caption">
        <h3>Georg Cantor</h3>
        <p>1845 - 1918</p>
      </div>
    </div>

    <div class="item">
      <img src="http://www.deism.com/images/Einstein_laughing.jpeg" alt="Einstein">
      <div class="carousel-caption">
        <h3>Albert Einstein</h3>
        <p>1879 - 1955</p>
      </div>
    </div>

    <div class="item">
      <img src="http://www.aphorism4all.com/images/1355816345.jpg" alt="Bohr">
      <div class="carousel-caption">
        <h3>Niels Bohr</h3>
        <p>1885 - 1962</p>
      </div>
    </div>

    <div class="item">
      <img src="https://wattsupwiththat.files.wordpress.com/2013/09/clip_image014_thumb1.jpg"   alt="Galileo">
      <div class="carousel-caption">
        <h3>Galileo Galilei</h3>
        <p>1564 - 1642</p>
      </div>
    </div>

    <div class="item">
      <img src="http://members.iif.hu/visontay/ponticulus/img1/portrait/maxwell-james-clerk2.jpg" alt="Maxwell">
      <div class="carousel-caption">
        <h3>James Clerk Maxwell</h3>
        <p>1831 - 1879</p>
      </div>
    </div>

    <div class="item">
      <img src="https://upload.wikimedia.org/wikipedia/commons/9/9b/Carl_Friedrich_Gauss.jpg" alt="Gauss">
      <div class="carousel-caption">
        <h3>Carl Friedrich Gauss</h3>
        <p>1777 - 1855</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome/home.html.erb
<h1>Theorem Check </h1>

<br><br><br><br><br>

<%= render partial: 'carousel' %>

<br><br>

<div class="frame">
  <div class="intro">
    <h3>This community is for all of you lovers of science, in all of its aspects. While looking for scintists, theorems and saving your favorites, help us enlarging our database creating new ones!</h3><br>
  </div>
</div>

app/views/welcome/todays.html.erb
<h1>Today's Creations:</h1>

<br><br><br><br><br>

<div class="frame">
  <div id="todays" class="intro">
    <div id="left">
      <% if !@scientists.empty? %>
        <% @scientists.each do |s| %>
          <h3><%= link_to s.full_name, s %></h3><br>
        <% end %>
      <% else %>
        <h3>Currently no scientists have been created today. Be the first today to <%= link_to "create", scientists_path %> a new one!</h3>
      <% end %>
    </div>
    <div id="right">
      <% if !@theorems.empty? %>
        <% @theorems.each do |t| %>
          <h3><%= link_to t.name, t %></h3><br>
        <% end %>
      <% else %>
        <h3>Currently no theorems have been created today. Be the first today to <%= link_to "create", theorems_path %> a new one!</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/top_3.html.erb
<h1>Top 3 Scientists</h1>

<br><br><br><br><br><br><br>

<div class="frame">
  <div class="scientists">
    <h3> 1) <%= link_to "#{@array[2][:name]}", link_to_scientist(2) %> - <%= @array[2][:count] %> users</h3>
    <h3> 2) <%= link_to "#{@array[1][:name]}", link_to_scientist(1) %> - <%= @array[1][:count] %> users</h3>
    <h3> 3) <%= link_to "#{@array[0][:name]}", link_to_scientist(0) %> - <%= @array[0][:count] %> users</h3>
  </div>
</div>