config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get '/created_today' => 'welcome#created_today'

  resources :subjects, except: :new do
    resources :areas, except: :index
  end

  resources :scientists do
    resources :quotes
  end
  resources :quotes
  get '/jolly' => 'welcome#jolly', :as => :jolly

  resources :scientists do
    resources :theorems
  end

  resources :theorems do
    resources :corollaries
  end

  post '/corollaries/:id/unsave_corollary' => 'corollaries#unsave_corollary', :as => :unsave_corollary
  post '/corollaries/:id/save_corollary' => 'corollaries#save_corollary', :as => :save_corollary
  get '/scientists/:id/unsave_scientist' => 'scientists#unsave_scientist', :as => :unsave_scientist
  get '/scientists/:id/save_scientist' => 'scientists#save_scientist', :as => :save_scientist
  get '/top_3' => 'welcome#top_3', :as => :top_3
  get '/theorems/:id/unsave_theorem' => 'theorems#unsave_theorem', :as => :unsave_theorem
  get '/theorems/:id/save_theorem' => 'theorems#save_theorem', :as => :save_theorem

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :destroy]
  get '/users/:id/make_admin' => 'users#make_admin'
  get '/users/:id/areas_created' => 'users#areas_created'
  get '/users/:id/subjects_created' => 'users#subjects_created'
  get '/users/:id/theorems_created' => 'users#theorems_created'
  get '/users/:id/scientists_created' => 'users#scientists_created'
end

app/models/theorem.rb
class Theorem < ApplicationRecord
  has_many :corollaries
  belongs_to :scientist
  belongs_to :area
  belongs_to :subject
  has_and_belongs_to_many :users

  validates_presence_of :statement
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  scope :created_today, -> {where("created_at >= ?", Date.today)}

  def area_attributes=(area_attributes)
    if self.area_id.nil?
      @area = Area.new(area_attributes)
      if @area.save
        self.area = @area
        self.subject = @area.subject
      end
    end
  end

  def scientist_attributes=(scientist_attributes)
    if self.scientist_id.nil?
      @scientist = Scientist.new(scientist_attributes)
      if @scientist.save
        self.scientist = @scientist
      end
    end
  end

  def self.top_3_theorems
    self.all.collect{|t| {name: t.name, count: t.users.count}}.sort{ |a,b| b.count <=> a.count }.last(3)
  end


  def self.search(search)
   where("name LIKE ?", "%#{search}%")
  end

end

app/controllers/theorems_controller.rb
class TheoremsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_theorem, only: [:show, :edit, :update, :destroy, :save_theorem, :unsave_theorem]
  before_action :set_scientist, only: [:new, :create]
  before_action :check_admin, only: [:edit, :destroy]

  def index
    if params[:search]
      @theorems = Theorem.search(params[:search]).order(name: :desc)
    elsif set_scientist
      @theorems = @scientist.theorems.sort { |a,b| a.name.downcase <=> b.name.downcase }
      render :template => "theorems/_theorems_display", layout: false
    else
      @theorems = Theorem.order(name: :desc)
    end
  end

  def show
  end

  def new
    if @scientist
      @theorem = @scientist.theorems.build
      @area = @theorem.build_area
    else
      @theorem = Theorem.new
      @area = @theorem.build_area
    end
    render layout: false 
  end

  def create
    if @scientist
      @theorem = @scientist.theorems.build(theorem_params)
    else
      @theorem = Theorem.new(theorem_params)
    end
    if @theorem.save
      respond_to do |format|
        format.js   {render :layout => false}
        format.html {redirect_to @theorem, notice: 'Theorem was successfully created.'}
      end
    else
      respond_to do |format|
        format.html { render 'new', notice: @theorem.errors.full_messages.first }
        format.js   { render json: @theorem.errors}
      end
    end
  end

  def edit
    render layout: false
  end

  def update
    if @theorem.update(theorem_params)
      respond_to do |format|
        format.html { redirect_to @theorem, notice: 'Theorem was successfully updated!'}
        format.js   { render :layout => false }
      end
    else
      respond_to do |format|
        format.html { render 'edit', notice: 'Oops!' }
        format.js   {}
      end
    end
  end

  def destroy
    @theorem.corollaries.each{|c| c.destroy}
    @theorem.destroy
    respond_to do |format|
      format.html { redirect_to theorems_path, notice: 'Theorem was successfully deleted!' }
      format.js   { render :layout => false }
    end
  end

  def save_theorem
    if current_user.add_to_fav(@theorem)
      redirect_to @theorem, notice: @theorem.name + " successfully added to Favorites"
    end
  end

  def unsave_theorem
    if current_user.remove_from_fav(@theorem)
      redirect_to @theorem, notice: @theorem.name + " successfully removed from Favorites"
    end
  end

  private

  def set_scientist
    @scientist = Scientist.find_by(id: params[:id]) || @scientist = Scientist.find_by(id: params[:scientist_id])
  end

  def set_theorem
    @theorem = Theorem.find(params[:id])
  end

  def theorem_params
    params.require(:theorem).permit(:name, :statement, :demonstration, :created_by, :scientist_id, :subject_id, :area_id, area_attributes: [:id, :name, :created_by, :subject_id], scientist_attributes: [:id, :full_name, :year_of_birth, :year_of_death, :created_by ])
  end
end

app/helpers/theorems_helper.rb
module TheoremsHelper
end

app/views/theorems/_classic_form.html.erb
<% if @theorem.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@theorem.errors.count, "error") %>
      prohibited this Theorem from being saved:
    </h2>
    <ul>
    <% @theorem.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>

<%= form_for @theorem, :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <h4><%= f.label :name, class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :name, :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :statement, class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :statement, :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :demonstration, class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :demonstration, class: "form-control" %>
    </div>
  </div>

  <br>

  <%= f.hidden_field :created_by, :value => current_user.email %>

  <h3>Select Scientist: </h3>

  <div class="form-group">
    <%= f.label :scientist_id, class: "col-md-4 control-label" %>
    <div class="col-md-4">
      <%= f.collection_select :scientist_id, Scientist.all, :id, :full_name, :include_blank => "Select Scientist" %>
    </div>
  </div>


  <%= f.fields_for :scientist do |scientist| %>
    <div class="form-group">
      <h4><%= scientist.label :full_name, "Full Name", class: "col-md-4 control-label" %></h4>
      <div class="col-md-4">
        <%= scientist.text_field :full_name, placeholder: "Name, Middle Name, Last Name", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <h4><%= scientist.label :year_of_birth, "Year of birth (YYYY): ", class: "col-md-4 control-label" %></h4>
      <div class="col-md-4">
        <%= scientist.number_field :year_of_birth, placeholder: 'Use negative numbers for BC years', class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <h4><%= scientist.label :year_of_death, "Year of death (YYYY): ", class: "col-md-4 control-label" %></h4>
      <div class="col-md-4">
        <%= scientist.number_field :year_of_death, placeholder: 'Leave blank if still alive', max: what_year_is_it?, :include_blank => true, class: "form-control" %>
      </div>
    </div>

    <br>

    <%= scientist.hidden_field :created_by, :value => current_user.email %>
  <% end %>


  <h3>Select Subject and Area: </h3>

  <div class="form-group">
    <%= f.label :subject_id, class: "col-md-4 control-label" %>
    <div class="col-md-4">
      <%= f.collection_select :subject_id, Subject.all, :id, :name, :include_blank => "Select Subject" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :area_id, class: "col-md-4 control-label" %>
    <div class="col-md-4">
      <%= f.collection_select :area_id, Area.all, :id, :name, :include_blank => "Select Area" %>
    </div>
  </div>


  <h3>Or create a new Area: </h3>

  <%= f.fields_for :area do |area| %>
    <div class="form-group">
      <%= area.label :name, "New Area", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= area.text_field :name, class: "form-control"  %>
      </div>
    </div>

    <div class="form-group">
      <%= area.label :subject_id, "And select the Subject", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= area.collection_select :subject_id, Subject.all, :id, :name, :include_blank => "Select Subject" %>
      </div>
    </div>

    <%= area.hidden_field :created_by, :value => current_user.email %>

  <% end %>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/theorems/_fav_buttons.html.erb
<% if resource_save?(resource) %>
  <div class="save-favorites-button">
    <%= link_to "Save", {:action => save(resource)}, class: "favs_green" %>
  </div>
<% else %>
  <div class="unsave-favorites-button">
    <%= link_to "Remove from Favorites", {:action => unsave(resource)}, class: "favs_red" %>
  </div>
<% end %>
</div>

app/views/theorems/_form.html.erb
<% if @theorem.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@theorem.errors.count, "error") %>
      prohibited this Theorem from being saved:
    </h2>
    <ul>
    <% @theorem.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>

<%= form_for [@scientist, @theorem], :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <h4><%= f.label :name, class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :name, :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :statement, class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :statement, :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :demonstration, class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :demonstration, class: "form-control" %>
    </div>
  </div>

  <br>

  <%= f.hidden_field :created_by, :value => current_user.email %>

  <h3>Select Subject and Area: </h3>

  <div class="form-group">
    <%= f.label :subject_id, class: "col-md-4 control-label" %>
    <div class="col-md-4">
      <%= f.collection_select :subject_id, Subject.all, :id, :name, :include_blank => "Select Subject" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :area_id, class: "col-md-4 control-label" %>
    <div class="col-md-4">
      <%= f.collection_select :area_id, Area.all, :id, :name, :include_blank => "Select Area" %>
    </div>
  </div>

  <h3>Or create a new Area: </h3>

  <%= f.fields_for :area do |area| %>
    <div class="form-group">
      <%= area.label :name, "New Area", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= area.text_field :name, class: "form-control"  %>
      </div>
    </div>

    <div class="form-group">
      <%= area.label :subject_id, "And select the Subject", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= area.collection_select :subject_id, Subject.all, :id, :name, :include_blank => "Select Subject" %>
      </div>
    </div>

    <%= area.hidden_field :created_by, :value => current_user.email %>

  <% end %>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/theorems/_search.html.erb
<div class="frame" style="width: 300px;">
  <div class="search-theorems">
    <%= form_tag(theorems_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Theorems by Name" %>
      <%= submit_tag "Search", class: "btn btn-primary", id: "button"%>
    <% end %>
  </div>
</div>

app/views/theorems/_theorem_info.html.erb
<div class="frame">
  <div id="theorem-info">

    <h3>Statement: </h3><h4><%= @theorem.statement %></h4><br>

    <h3>Demonstration: </h3><h4><%= no_proof?(@theorem) %></h4><br>

    <h3>Scientist: </h3><h4><%= link_to @theorem.scientist.full_name, @theorem.scientist %></h4><br>

    <h3>Subject: </h3><h4><%= link_to @theorem.subject.name, @theorem.subject %></h4><br>

    <h3>Area: </h3><h4><%= link_to @theorem.area.name, subject_area_path(@theorem.subject, @theorem.area) %></h4><br>

    <% if current_user.admin? %>
      <h3>Added by: </h3><h4><%= link_to @theorem.created_by, user_by_email(@theorem.created_by) %></h3>
    <% end %>
  </div>
</div>

app/views/theorems/_theorem_summary.html.erb
<div class="theorem" id="theorem-<%= theorem.id%>">
  <h3><%= link_to theorem.name, theorem %></h3>
  <div class="theorem-statement"><%= truncate theorem.statement %></div>
  <% if current_user.admin? %>
    <strong><p>Created by: <%= link_to theorem.created_by, user_by_email(theorem.created_by) %></p></strong>
    <div id="edit-<%= theorem.id%>" style="display: inline;"><strong><%= link_to "Edit", edit_theorem_path(theorem), class: "btn btn-primary btn-xs", id: "edit-button" %></strong></div>
    <div id="delete-<%= theorem.id%>" style="display: inline;"><strong><%= button_to "Destroy", theorem_path(theorem), class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"} %></strong></div>
    <div id="edit-theorem-<%= theorem.id%>-div"></div>
  <% end %>
  <div id="line" style="margin-right:auto; margin-left:auto;"></div>
</div>

app/views/theorems/_theorems_display.html.erb
<div class="frame">
  <div class="all-theorems">

    <ul>
      <% if !@theorems.empty? %>
        <% @theorems.each do |t| %>
          <%= render partial: 'theorem_summary', locals: {theorem: t } %><br>
        <% end %>
      <% end %>
    </ul>

  </div>
</div>

app/views/theorems/create.js.erb
var html = "<%= j render 'theorems/theorem_summary', theorem: @theorem %>"
if (document.getElementById("empty-space")) {
  $('h3#empty-space').replaceWith(html)
  $('form#new_theorem').reset();
  $('#form_for_theorem').hide();
} else {
  $(".all-theorems ul").append(html)
  $('#form_for_theorem').hide();
}

app/views/theorems/edit.html.erb
<div class="frame">
  <div class="new-theorem-form">
    <%= render partial: 'form', locals: { scientist: @scientist, theorem: @theorem} %>
  </div>
</div>

app/views/theorems/edit.js.erb
if( $("#edit-theorem-<%= @theorem.id%>-div").children().length == 0 ) {
  $("#edit-theorem-<%= @theorem.id%>-div").html("<%= j render 'theorems/form', theorem: @theorem %>");
} else {
  $("#edit-theorem-<%= @theorem.id%>-div").toggle();
}

app/views/theorems/index.html.erb
<h1>Theorems:</h1>

<br><br><br><br>

<%= render partial: 'search'%>

<br><br>

<% if @theorems.present? %>
  <%= render partial: 'theorems_display', locals: {theorems: @theorems} %>
<% elsif !@theorems.present? &&  params[:search] %>
  <div class="frame">
    <div id="theorem-info" style="text-align: center;">
      <h3>There are no theorems containing the term(s) "<%= params[:search] %>".</h3>
    </div>
  </div>
<% else %>
  <div class="frame">
    <div id="theorem-info" style="text-align: center;">
      <h3 id="empty-space">Currently there are no theorems to show</h3>
    </div>
  </div>
<% end %>

<br><br>

<%= link_to "New Theorem", new_theorem_path, class: "btn btn-primary", id: "new_theorem_form_div" %>

<div id="div_for_form" style="display: none;"></div>

app/views/theorems/new.js.erb
var html = "<%= j render 'theorems/form', theorem: @theorem %>"
if ($("#div_for_form").children().length == 0) {
  $('#div_for_form').append("<div class='frame'><div class='centered'></div></div>")
  $('.centered').append(html)
} else {
  $('#div_for_form').toggle()
}

app/views/theorems/show.html.erb
<h1><%= @theorem.name %></h1>

<br><br><br><br><br><br><br><br><br>

<%= render partial: "fav_buttons", locals: {resource: @theorem} %>

<%= render partial: 'theorem_info', locals: {theorem: @theorem } %><br>

<div class="back-button">
  <%= link_to "Corollaries", theorem_corollaries_path(@theorem), class: "btn btn-primary", id: "corollaries_button"%>
  &nbsp&nbsp&nbsp&nbsp
  <%= link_to "New Corollary", new_theorem_corollary_path(@theorem), class: "btn btn-primary", id: "new_corollary_button"%>
</div>

<div id="corollaries" style="display: none;"></div>

<div id="new_corollary_section" style="display: none;"></div>

app/views/theorems/update.js.erb
$("#theorem-<%= @theorem.id%>").html("<%= j render 'theorems/theorem_summary', theorem: @theorem %>");
$("#edit-theorem-<%= @theorem.id%>-div").hide();