config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get '/created_today' => 'welcome#created_today'

  resources :subjects, except: :new do
    resources :areas, except: :index
  end

  resources :scientists do
    resources :quotes
  end
  resources :quotes
  get '/jolly' => 'welcome#jolly', :as => :jolly

  resources :scientists do
    resources :theorems
  end

  resources :theorems do
    resources :corollaries
  end

  post '/corollaries/:id/unsave_corollary' => 'corollaries#unsave_corollary', :as => :unsave_corollary
  post '/corollaries/:id/save_corollary' => 'corollaries#save_corollary', :as => :save_corollary
  get '/scientists/:id/unsave_scientist' => 'scientists#unsave_scientist', :as => :unsave_scientist
  get '/scientists/:id/save_scientist' => 'scientists#save_scientist', :as => :save_scientist
  get '/top_3' => 'welcome#top_3', :as => :top_3
  get '/theorems/:id/unsave_theorem' => 'theorems#unsave_theorem', :as => :unsave_theorem
  get '/theorems/:id/save_theorem' => 'theorems#save_theorem', :as => :save_theorem

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show, :destroy]
  get '/users/:id/make_admin' => 'users#make_admin'
  get '/users/:id/areas_created' => 'users#areas_created'
  get '/users/:id/subjects_created' => 'users#subjects_created'
  get '/users/:id/theorems_created' => 'users#theorems_created'
  get '/users/:id/scientists_created' => 'users#scientists_created'
end

app/models/scientist.rb
class Scientist < ApplicationRecord
  has_many :theorems
  has_many :corollaries, through: :theorems
  has_many :areas, through: :theorems
  has_many :subjects, through: :theorems
  has_and_belongs_to_many :users
  has_many :quotes

  validates :full_name, presence: true, uniqueness: { case_sensitive: false }
  validates :year_of_birth, presence: true
  validate :year_of_birth_cannot_be_in_the_future
  validate :birth_comes_before_death

  scope :created_today, -> {where("created_at >= ?", Date.today)}


  def theorems_attributes=(theorems_attributes)
    theorems_attributes.each do |k, v|
      @theorem = self.theorems.build(name: v['name'])
      @theorem.statement = v['statement']
      @theorem.demonstration = v['demonstration']
      @theorem.created_by = v['created_by']
      if v['area_id'].empty?
        @area = Area.new(v['area_attributes'])
        @area.subject = Subject.find_by(id: v['area_attributes']['subject_id'])
        @area.save
        @theorem.area = @area
        @theorem.subject = @area.subject
        @theorem.save
      else
        @area = Area.find_by(id: v['area_id'])
        @theorem.area = @area
        @theorem.subject = @area.subject
        @theorem.save
      end
    end
  end

  def year_of_birth_cannot_be_in_the_future
    if year_of_birth > Date.today.year
      errors.add(:year_of_birth, "Can't be in the future")
    end
  end

  def birth_before_christ?
    year_of_birth < 0 ? (year_of_birth.abs.to_s + " BC") : year_of_birth
  end

  def death_before_christ?
    if year_of_death
      if year_of_death.to_f < 0
        return year_of_death.abs.to_s + " BC"
      else
        return year_of_death
      end
    else
      return "Still among us!"
    end
  end

  def birth_comes_before_death
    if year_of_birth > year_of_death
      errors.add(:year_of_birth, "Must be before Year of Death")
    end
  end

  def self.search(search)
   where("full_name LIKE ?", "%#{search}%")
  end

  def self.top_3_scientists
    self.all.collect{|s| {name: s.full_name, count: s.users.count}}.sort{ |a,b| b.count <=> a.count }.last(3)
  end
end

app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_scientist, only: [:show, :edit, :update, :destroy, :save_scientist, :unsave_scientist]
  before_action :check_admin, only: [:edit, :destroy]

  def index
    if params[:search]
      @scientists = Scientist.search(params[:search]).order(full_name: :desc)
    else
      @scientists = Scientist.order(full_name: :desc)
    end
  end

  def show
    @theorem = @scientist.theorems.build
  end

  def new
    @scientist = Scientist.new
    @theorem = @scientist.theorems.build
    @area = @theorem.build_area
    render :layout => false
  end


  def create
    @scientist = Scientist.new(scientist_params)
    if @scientist.save
      respond_to do |format|
        format.js   {render :layout => false}
        format.html {redirect_to @scientist, notice: 'Scientist, Theorem and area were successfully created.'}
      end
    else
      respond_to do |format|
        format.html { render 'new', notice: @scientist.errors.full_messages.first }
        format.js   { render json: @scientist.errors}
      end
    end
  end

  def edit
    respond_to do |format|
      format.html { redirect_to edit_scientist_path(@scientist) }
      format.js   { render :layout => false }
    end
  end

  def update
    if @scientist.update(scientist_params)
      respond_to do |format|
        format.html { redirect_to @scientist, notice: 'Scientist was successfully updated!'}
        format.js   { render :layout => false }
      end
    else
      respond_to do |format|
        format.html { render 'edit', notice: 'Oops!' }
        format.js   {}
      end
    end
  end

  def destroy
    @scientist.theorems.each{ |t| t.destroy }
    @scientist.corollaries.each{|c| c.destroy}
    @scientist.quotes.each{ |q| q.destroy }
    @scientist.destroy
    respond_to do |format|
      format.html { redirect_to scientists_path, notice: 'Scientist was successfully deleted!' }
      format.js   { render :layout => false }
    end
  end

  def save_scientist
    if current_user.add_to_fav(@scientist)
      redirect_to @scientist, notice: @scientist.full_name + " successfully added to Favorites"
    end
  end

  def unsave_scientist
    if current_user.remove_from_fav(@scientist)
      redirect_to @scientist, notice: @scientist.full_name + " successfully removed from Favorites"
    end
  end

  private

  def set_scientist
    @scientist = Scientist.find(params[:id]) || @scientist = Scientist.find(params[:scientist_id])
  end

  def scientist_params
    params.require(:scientist).permit(:full_name, :year_of_birth, :year_of_death, :created_by, theorems_attributes: [:id, :name, :statement, :demonstration, :created_by, :scientist_id, :subject_id, :area_id, area_attributes:[:id, :name, :created_by, :subject_id]])
  end
end

app/helpers/scientists_helper.rb
module ScientistsHelper

  def what_year_is_it?
    Time.now.year
  end

  def condition(collection)
    collection == "theorems" ? (return true if @scientist.theorems.count > 3) : (return true if @scientist.quotes.count > 3)
  end
end

app/views/scientists/_edit_form.html.erb
<% if @scientist.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@scientist.errors.count, "error") %>
      prohibited this Scientist from being saved:
    </h2>
    <ul>
    <% @scientist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>

<%= form_for @scientist, :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <h4><%= f.label :full_name, "Full Name", class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :full_name, placeholder: "Name, Middle Name, Last Name", :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :year_of_birth, "Year of birth (YYYY): ", class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.number_field :year_of_birth, placeholder: 'Use negative numbers for BC years', :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :year_of_death, "Year of death (YYYY): ", class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.number_field :year_of_death, placeholder: 'Leave blank if still alive', max: what_year_is_it?, :include_blank => true, class: "form-control" %>
    </div>
  </div>

  <br>

  <%= f.hidden_field :created_by, :value => current_user.email %>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/scientists/_form.html.erb
<% if @scientist.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@scientist.errors.count, "error") %>
      prohibited this Scientist from being saved:
    </h2>
    <ul>
    <% @scientist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>

<%= form_for @scientist, :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <h4><%= f.label :full_name, "Full Name", class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.text_field :full_name, placeholder: "Name, Middle Name, Last Name", :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :year_of_birth, "Year of birth (YYYY): ", class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.number_field :year_of_birth, placeholder: 'Use negative numbers for BC years', :required => true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :year_of_death, "Year of death (YYYY): ", class: "col-md-4 control-label" %></h4>
    <div class="col-md-4">
      <%= f.number_field :year_of_death, placeholder: 'Leave blank if still alive', max: what_year_is_it?, :include_blank => true, class: "form-control" %>
    </div>
  </div>

  <br>

  <%= f.hidden_field :created_by, :value => current_user.email %>

  <h3>Create the first theorem: </h3>

  <%= f.fields_for :theorems do |theorem| %>
    <div class="form-group">
      <%= theorem.label :name, "Theorem Name", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= theorem.text_field :name, :required => true %>
      </div>
    </div>

    <div class="form-group">
      <%= theorem.label :statement, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= theorem.text_area :statement, :required => true %>
      </div>
    </div>

    <div class="form-group">
      <%= theorem.label :demonstration, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= theorem.text_area :demonstration %>
      </div>
    </div>

    <%= theorem.hidden_field :created_by, :value => current_user.email %>

    <div class="form-group">
      <%= theorem.label :area_id, class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= theorem.collection_select :area_id, Area.all, :id, :name, :include_blank => "Select Area" %>
      </div>
    </div>

    <%= theorem.fields_for :area do |area| %>
      <div class="form-group">
        <%= area.label :name, "Or Create New Area", class: "col-md-4 control-label" %>
        <div class="col-md-4">
          <%= area.text_field :name %>
        </div>
      </div>

      <div class="form-group">
        <%= area.label :subject_id, "And select a Subject", class: "col-md-4 control-label" %>
        <div class="col-md-4">
          <%= area.collection_select :subject_id, Subject.all, :id, :name, :include_blank => "Select Subject" %>
        </div>
      </div>

      <%= area.hidden_field :created_by, :value => current_user.email %>

    <% end %>
  <% end %>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/scientists/_scientist_quotes.html.erb
<ul>
  <% if @scientist.quotes.count == 0  %>
    <h3>No quotes to display</h3>
  <% else %>
    <h3>Quotes:</h3><br>
    <% @scientist.quotes.take(3).each do |q| %>
      <h4><%= link_to (truncate q.text), scientist_quote_path(@scientist, q) %></h4>
      By: <strong><%= link_to @scientist.full_name, @scientist %></strong>
      <div class="admin-info">
        <% if current_user.admin? %>
          <strong><p>Created by: <%= link_to q.created_by, user_by_email(q.created_by) %></p></strong>
          <strong><%= link_to "Edit", edit_scientist_quote_path(@scientist, q), class: "btn btn-primary btn-xs" %>  <%= button_to "Destroy", [@scientist, q], class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"} %></strong>
        <% end %>
      </div>
      <div id="line"></div>
    <% end %>
  <% end %>
</ul>

<% if condition("scientists") %>
  <%= link_to "See all quotes", scientist_quotes_path(@scientist), class: "btn btn-primary", id: "index_quote"%>
<% end %>
<br><br>

app/views/scientists/_scientist_summary.html.erb
<div class="scientist" id="scientist-<%= scientist.id%>">
  <h3><%= link_to scientist.full_name, scientist %></h3><br>
  <div class="admin-info">
    <% if current_user.admin? %>
      <strong><p>Created by: <%= link_to scientist.created_by, user_by_email(scientist.created_by) %></p></strong>
      <div id="edit-<%= scientist.id%>" style="display: inline;"><strong><%= link_to "Edit", edit_scientist_path(scientist), class: "btn btn-primary btn-xs", id: "edit-button" %></strong></div>
      <div id="delete-<%= scientist.id%>" style="display: inline;"><strong><%= button_to "Destroy", scientist, class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"} %></strong></div>
      <div id="edit-scientist-<%= scientist.id%>-div"></div>
    <% end %>
  </div>
  <div id="line" style="margin-right:auto; margin-left:auto;"></div>
</div>

app/views/scientists/_search.html.erb
<div class="frame" style="width: 300px;">
  <div class="search-scientists">
    <%= form_tag(scientists_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Scientists by Name" %>
      <%= submit_tag "Search", class: "btn btn-primary", id: "button"%>
    <% end %>
  </div>
</div>

app/views/scientists/create.js.erb
var html = "<%= j render 'scientists/scientist_summary', scientist: @scientist %>"
if (document.getElementById("empty_list")) {
  $('h3#empty_list').replaceWith(html);
  $('form#new_scientist').reset();
  $('#form_div').hide();
} else {
  $(".scientists ul").append(html);
  $('#form_div').hide();
}

app/views/scientists/destroy.js.erb
$('div#scientist-<%=@scientist.id %>').remove();

app/views/scientists/edit.html.erb
<h1>Edit <%= @scientist.full_name %></h1>

<br><br><br><br><br><br><br><br>

<div class="frame">
  <div class="new-scientist-form">
    <%= render partial: 'edit_form', locals: {scientist: @scientist} %>
  </div>
</div>

app/views/scientists/edit.js.erb
$('body').off('click');
if( $("#edit-scientist-<%= @scientist.id%>-div").children().length == 0 ) {
  $("#edit-scientist-<%= @scientist.id%>-div").html("<%= j render 'scientists/form', scientist: @scientist %>");
} else {
  $("#edit-scientist-<%= @scientist.id%>-div").toggle();
}

app/views/scientists/index.html.erb
<h1>Scientists: </h1>

<br><br><br><br>

<%= render partial: 'search'%>

<br><br>

<% if @scientists.present? %>
  <%= render partial: 'scientists', locals: {scientists: @scientists} %>
<% elsif !@scientists.present? &&  params[:search] %>
  <div class="frame">
    <div class="scientists" style="text-align: center;">
      <h3>There are no scientists containing the term(s) "<%= params[:search] %>".</h3>
    </div>
  </div>
<% else %>
  <div class="frame">
    <div class="scientists" style="text-align: center;">
      <h3 id="empty_list">Currently there are no scientists to show</h3>
    </div>
  </div>
<% end %>

<br>

<%= link_to "New Scientist", new_scientist_path, class: "btn btn-primary", id: "new_scientist_form" %>

<div id="form_div">
</div>

app/views/scientists/new.html.erb
<div class="frame">
  <div class="new-scientist-form">
    <%= render partial: 'form', locals: {scientist: @scientist} %>
  </div>
</div>

app/views/scientists/show.html.erb
<h1><%= @scientist.full_name %></h1>

<br><br><br><br><br><br>

<%= render partial: "/theorems/fav_buttons", locals: {resource: @scientist} %>


<br><br>

<div class="frame-too">
  <h3><div class="centered">(Year of Birth: <%= @scientist.birth_before_christ? %> - Year of Death: <%= @scientist.death_before_christ? %>)</div></h3><br>
</div>

<br><br><br><br>


<div class="scientist-buttons">
  <%= link_to "Quotes", scientist_quotes_path(@scientist), class: "btn btn-primary", id: "index_quote"%>
  <%= link_to "New Quote", new_scientist_quote_path(@scientist, @quote), class: "btn btn-primary", id: "new_quote_form"%>
  <%= link_to "All theorems", scientist_theorems_path(@scientist), class: "btn btn-primary", id: "index_theorems"%>
  <%= link_to "New Theorem", new_scientist_theorem_path(@scientist, @theorem), class: "btn btn-primary", id: "nested_theorem_form"%>
</div>

<div id="quotes_by_scientist"></div>

<div id="form_for_quote"></div>

<div id="theorems_by_scientist"></div>

<div id="form_for_theorem"></div>

app/views/scientists/top_3.html.erb
<h1>Our Top 3</h1>

<br><br><br><br><br><br><br>

<div class="top_3">
  <div class="top_scientists">
    <h2>Scientists:</h2>
    <h3><%= link_to "#{@scientists_array[2][:name]}", find_scientist(2) %></h3>  <strong><%= @scientists_array[2][:count] %> users</strong>
    <h3><%= link_to "#{@scientists_array[1][:name]}", find_scientist(1) %></h3>  <strong><%= @scientists_array[1][:count] %> users</strong>
    <h3><%= link_to "#{@scientists_array[0][:name]}", find_scientist(0) %></h3>  <strong><%= @scientists_array[0][:count] %> users</strong>
  </div>

  <div class="top_theorems">
    <h2>Theorems:</h2>
    <h3><%= link_to "#{@theorems_array[2][:name]}", find_theorem(2) %></h3>  <strong><%= @theorems_array[2][:count] %> users</strong>
    <h3><%= link_to "#{@theorems_array[1][:name]}", find_theorem(1) %></h3>  <strong><%= @theorems_array[1][:count] %> users</strong>
    <h3><%= link_to "#{@theorems_array[0][:name]}", find_theorem(0) %></h3>  <strong><%= @theorems_array[0][:count] %> users</strong>
  </div>
</div>

app/views/scientists/update.js.erb
$("#scientist-<%= @scientist.id%>").html("<%= j render 'scientists/scientist_summary', scientist: @scientist %>");
$("#edit-scientist-<%= @scientist.id%>-div").hide();